config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :items
  resources :list_items
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'items#index'
  

  # get 'store/index'
  # EXAMPLE HTML ROUTE
  # get "/photos" => "photos#index"

  # EXAMPLE JSON ROUTE WITH API NAMESPACE
  # namespace :api do
  #   get "/photos" => "photos#index"
  # end
end

app/models/item.rb
class Item < ActiveRecord::Base
  # mount_uploaders :images, ImageUploader
  # serialize :images, JSON # If you use SQLite, add this line.
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :line_items
  mount_uploader :image, ImageUploader


  validates :title, :price, :condition, presence: true
  validates :description, length: { maximum: 500, too_long: "%{count} chraracters is the maximum allowed."}
  validates :title, length: { maximum: 140, too_long: "%{count} chraracters is the maximum allowed."}
  validates :price, length: { maximum: 7 }
  
  CONDITION = %w{ New Mint Good Used Fair Poor }

  private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /items
  # GET /items.json



  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        p "Fu..n."
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :condition, :price, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  
  def item_author(item)
    user_signed_in? && current_user.id == item.user_id
  end

end

app/views/items/_form.html.erb
<div class="columns">
  <div class="column is-7 is-centered">

    <%= simple_form_for @item, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-10">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column is-2">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field column is-12">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>


          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Item::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field column">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input item-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />
        </div>
        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', items_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Art Object
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Support Some Good on Naniel
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="item-index-grid pt4">
  <% @items.each do |item| %>

    <div class="item border-light">
      <div class="item-thumb">
      <%= link_to image_tag(item.image_url(:thumb)), item %>

      <% if item.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= item.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to item.title, item %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= item.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(item.price) %></p>

      <% if item_author(item) %>
         <%= link_to 'Edit', edit_item_path(item), class: "button is-small" %>
         <%= link_to 'Delete', item, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/items/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell An Art Object
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section item-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @item.title %></h1>

      <ul class="pv1">

  

        <% if @item.condition? %>
        <li class="inline-block pr3"><%= @item.condition %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@item.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @item.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @item.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @item.condition %></td>
        </tr>
        <% end %>


        <% if @item.description %>
          <tr>
            <td class="has-text-weight-bold">Description:</td>
            <td><%= @item.description %></td>
          </tr>
        <% end %>


      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@item.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @item.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(item_id: @item), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if item_author(@item) %>
    <%= link_to 'Edit', edit_item_path(@item), class: 'button' %>
  <% end %>
</section>